spring:
  application:
    name: bankend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/imf-post
    dirver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 76993965996@Mysql
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
